In [1]:
import numpy as np
import pandas as pd

# Load du df depuis BQ

In [42]:
from google.cloud import bigquery
from google.oauth2 import service_account
import sys; sys.path.append('..')
from params import PROJECT_ID, TABLE_ID

def load_dataset(PROJECT_ID, TABLE_ID):

    print(PROJECT_ID, TABLE_ID)

    TABLE_ID = 'test_dataset.test10'

    credentials = service_account.Credentials.from_service_account_file("../bq_keys.json")
    #credentials = service_account.Credentials.from_service_account_file('~//Users//admin/code//tloizel//wagon-give-me-a-sign//bq_keys.json')

    client = bigquery.Client(project=PROJECT_ID, credentials=credentials)
    table = client.get_table(TABLE_ID)


    # Construct the SQL query to retrieve the table data
    query = f'SELECT * FROM `{table}`'

    # Submit the query and fetch the results
    df = client.query(query).to_dataframe()
    
    return df

In [44]:
df = load_dataset(PROJECT_ID, TABLE_ID)
df.head(3)

wagon-give-me-a-sign test_dataset.test10'    #TABLE_ID = 'test_dataset.test26

,x_0,y_0,z_0,x_1,y_1,z_1,x_2,y_2,z_2,x_3,...,x_18,y_18,z_18,x_19,y_19,z_19,x_20,y_20,z_20,target
0,0.0,0.0,0.0,0.068996,-0.001794,-0.026495,0.129794,-0.049328,-0.037758,0.157946,...,0.015763,-0.236859,-0.053696,0.014897,-0.160986,-0.042879,0.003309,-0.143430,-0.028293,a
1,0.0,0.0,0.0,0.084189,-0.004527,-0.035077,0.159894,-0.063521,-0.049802,0.195749,...,0.022846,-0.301951,-0.067628,0.019003,-0.205834,-0.053242,0.004331,-0.182658,-0.034498,a
2,0.0,0.0,0.0,0.081866,0.003673,-0.039060,0.166663,-0.060628,-0.056427,0.204637,...,0.011525,-0.315707,-0.082841,0.011519,-0.209255,-0.069801,-0.000003,-0.184926,-0.051607,a

In [10]:
df[df['target'] == 'a']

,x_0,y_0,z_0,x_1,y_1,z_1,x_2,y_2,z_2,x_3,...,x_18,y_18,z_18,x_19,y_19,z_19,x_20,y_20,z_20,target
0,0.0,0.0,0.0,0.068996,-0.001794,-0.026495,0.129794,-0.049328,-0.037758,0.157946,...,0.015763,-0.236859,-0.053696,0.014897,-0.160986,-0.042879,0.003309,-0.143430,-0.028293,a
1,0.0,0.0,0.0,0.084189,-0.004527,-0.035077,0.159894,-0.063521,-0.049802,0.195749,...,0.022846,-0.301951,-0.067628,0.019003,-0.205834,-0.053242,0.004331,-0.182658,-0.034498,a
2,0.0,0.0,0.0,0.081866,0.003673,-0.039060,0.166663,-0.060628,-0.056427,0.204637,...,0.011525,-0.315707,-0.082841,0.011519,-0.209255,-0.069801,-0.000003,-0.184926,-0.051607,a
3,0.0,0.0,0.0,0.072380,0.001230,-0.018210,0.133630,-0.037806,-0.024918,0.162663,...,0.032818,-0.254179,-0.044583,0.030884,-0.179450,-0.034737,0.014321,-0.144736,-0.021350,a
4,0.0,0.0,0.0,0.087307,-0.013774,-0.015136,0.145934,-0.070759,-0.021705,0.181889,...,0.044853,-0.331586,-0.057311,0.039559,-0.234893,-0.044078,0.012328,-0.194194,-0.025516,a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,0.0,0.0,0.0,0.089020,-0.004631,-0.040117,0.173419,-0.068980,-0.058396,0.211823,...,0.015739,-0.327877,-0.080195,0.015405,-0.222312,-0.064478,-0.000278,-0.202003,-0.044425,a
206,0.0,0.0,0.0,0.076448,-0.024823,-0.019830,0.134515,-0.093043,-0.027526,0.156989,...,0.006143,-0.281344,-0.046327,0.004280,-0.202661,-0.035166,-0.000106,-0.154207,-0.019415,a
207,0.0,0.0,0.0,0.051935,0.004076,-0.021560,0.104980,-0.037268,-0.027891,0.130062,...,0.009148,-0.201698,-0.032603,0.009347,-0.139441,-0.025672,0.004016,-0.114325,-0.014465,a
208,0.0,0.0,0.0,0.075985,-0.012906,-0.024148,0.136739,-0.065944,-0.034568,0.169121,...,0.014171,-0.263591,-0.055377,0.012828,-0.183512,-0.043389,0.003203,-0.158895,-0.027436,a
209,0.0,0.0,0.0,0.074415,-0.013738,-0.031449,0.138998,-0.070719,-0.044023,0.169419,...,0.003324,-0.264689,-0.053460,0.004267,-0.183576,-0.042859,-0.001866,-0.155362,-0.027300,a

In [11]:
df[df['target'] == 'b']

,x_0,y_0,z_0,x_1,y_1,z_1,x_2,y_2,z_2,x_3,...,x_18,y_18,z_18,x_19,y_19,z_19,x_20,y_20,z_20,target
420,0.0,0.0,0.0,0.063047,-0.023764,-0.015633,0.111474,-0.126108,-0.015273,0.117327,...,0.018098,-0.390239,-0.032541,0.029245,-0.455837,-0.041731,0.036757,-0.515435,-0.048519,b
421,0.0,0.0,0.0,0.077677,-0.029166,-0.024637,0.133963,-0.135797,-0.028595,0.128716,...,0.006046,-0.404690,-0.049162,0.017995,-0.475040,-0.063089,0.028325,-0.541893,-0.073049,b
422,0.0,0.0,0.0,0.063846,-0.015011,-0.023965,0.114944,-0.101225,-0.026450,0.109210,...,0.022602,-0.338525,-0.024050,0.034710,-0.392095,-0.035076,0.044988,-0.442140,-0.043324,b
423,0.0,0.0,0.0,0.062339,-0.023871,-0.021267,0.113165,-0.107567,-0.023207,0.111182,...,0.019820,-0.321470,-0.022635,0.030051,-0.370892,-0.031228,0.038455,-0.418239,-0.038222,b
424,0.0,0.0,0.0,0.064134,-0.028756,-0.022028,0.113750,-0.114887,-0.023899,0.109048,...,0.016710,-0.330782,-0.018656,0.026637,-0.383943,-0.028698,0.034285,-0.432992,-0.036586,b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,0.0,0.0,0.0,0.058419,-0.030207,-0.015475,0.099631,-0.108319,-0.016353,0.097771,...,0.015726,-0.307548,-0.022291,0.024386,-0.356151,-0.029392,0.031174,-0.400676,-0.034954,b
626,0.0,0.0,0.0,0.060126,-0.017372,-0.013335,0.105420,-0.098992,-0.012475,0.108897,...,0.029067,-0.332348,-0.025400,0.040817,-0.387573,-0.033769,0.049316,-0.437535,-0.039949,b
627,0.0,0.0,0.0,0.070404,-0.006071,-0.017204,0.135407,-0.109200,-0.017203,0.149792,...,0.051218,-0.426427,-0.046215,0.069479,-0.499157,-0.057802,0.083838,-0.569521,-0.065745,b
628,0.0,0.0,0.0,0.068547,-0.012165,-0.014034,0.125481,-0.104795,-0.012689,0.135076,...,0.048240,-0.398056,-0.035419,0.063773,-0.464220,-0.046029,0.074907,-0.525973,-0.053582,b
629,0.0,0.0,0.0,0.064126,-0.020897,-0.023634,0.111174,-0.106944,-0.024843,0.109917,...,0.018873,-0.320796,-0.013422,0.030369,-0.371408,-0.024301,0.039568,-0.417912,-0.033064,b

In [12]:
df[df['target'] == 'c']

,x_0,y_0,z_0,x_1,y_1,z_1,x_2,y_2,z_2,x_3,...,x_18,y_18,z_18,x_19,y_19,z_19,x_20,y_20,z_20,target
210,0.0,0.0,0.0,0.074740,-0.005406,0.011533,0.129689,-0.070941,0.016830,0.164919,...,0.097903,-0.379270,-0.033036,0.135918,-0.362435,-0.037971,0.153537,-0.315532,-0.037863,c
211,0.0,0.0,0.0,0.058287,0.002335,0.003196,0.103122,-0.042353,0.007224,0.129175,...,0.072050,-0.293571,-0.014275,0.098791,-0.282593,-0.019037,0.109129,-0.244201,-0.019453,c
212,0.0,0.0,0.0,0.070365,-0.011590,0.013311,0.122582,-0.086196,0.016351,0.161438,...,0.090617,-0.394149,-0.055463,0.132981,-0.363918,-0.059314,0.148968,-0.308942,-0.057448,c
213,0.0,0.0,0.0,0.067062,-0.013349,0.013964,0.116662,-0.081406,0.017737,0.151236,...,0.087692,-0.372226,-0.050658,0.127769,-0.342820,-0.055277,0.144033,-0.288455,-0.054999,c
214,0.0,0.0,0.0,0.064259,-0.009375,0.003520,0.116067,-0.072512,0.004304,0.148065,...,0.062640,-0.366870,-0.032594,0.098788,-0.353422,-0.037707,0.116162,-0.305608,-0.037380,c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,0.0,0.0,0.0,0.062432,-0.003917,0.001934,0.115769,-0.071857,0.002907,0.148040,...,0.060754,-0.374619,-0.035848,0.099967,-0.358185,-0.040228,0.116540,-0.308916,-0.038077,c
416,0.0,0.0,0.0,0.067867,-0.006935,0.015609,0.114691,-0.057831,0.022275,0.145509,...,0.083861,-0.335960,-0.028267,0.116998,-0.319782,-0.031475,0.133911,-0.276201,-0.030894,c
417,0.0,0.0,0.0,0.069791,-0.011537,0.012637,0.120119,-0.079101,0.016036,0.155316,...,0.086661,-0.374195,-0.053077,0.127038,-0.347239,-0.056947,0.142280,-0.294635,-0.055391,c
418,0.0,0.0,0.0,0.071314,-0.007569,0.014654,0.120373,-0.059978,0.021179,0.152055,...,0.092074,-0.346407,-0.030822,0.126158,-0.330693,-0.035048,0.140579,-0.284686,-0.035262,c
419,0.0,0.0,0.0,0.066761,-0.002139,0.002527,0.122181,-0.067481,0.002612,0.157885,...,0.067176,-0.374349,-0.042604,0.108648,-0.355112,-0.048795,0.128903,-0.303140,-0.047777,c

In [15]:
df.columns

Index(['x_0', 'y_0', 'z_0', 'x_1', 'y_1', 'z_1', 'x_2', 'y_2', 'z_2', 'x_3',
       'y_3', 'z_3', 'x_4', 'y_4', 'z_4', 'x_5', 'y_5', 'z_5', 'x_6', 'y_6',
       'z_6', 'x_7', 'y_7', 'z_7', 'x_8', 'y_8', 'z_8', 'x_9', 'y_9', 'z_9',
       'x_10', 'y_10', 'z_10', 'x_11', 'y_11', 'z_11', 'x_12', 'y_12', 'z_12',
       'x_13', 'y_13', 'z_13', 'x_14', 'y_14', 'z_14', 'x_15', 'y_15', 'z_15',
       'x_16', 'y_16', 'z_16', 'x_17', 'y_17', 'z_17', 'x_18', 'y_18', 'z_18',
       'x_19', 'y_19', 'z_19', 'x_20', 'y_20', 'z_20', 'target'],
      dtype='object')

## Features

In [23]:
X = df.drop(columns=['x_0', 'y_0', 'z_0', 'target'])
X.head(3)

,x_1,y_1,z_1,x_2,y_2,z_2,x_3,y_3,z_3,x_4,...,z_17,x_18,y_18,z_18,x_19,y_19,z_19,x_20,y_20,z_20
0,0.068996,-0.001794,-0.026495,0.129794,-0.049328,-0.037758,0.157946,-0.134318,-0.046930,0.166053,...,-0.026416,0.015763,-0.236859,-0.053696,0.014897,-0.160986,-0.042879,0.003309,-0.143430,-0.028293
1,0.084189,-0.004527,-0.035077,0.159894,-0.063521,-0.049802,0.195749,-0.165570,-0.061154,0.206228,...,-0.034393,0.022846,-0.301951,-0.067628,0.019003,-0.205834,-0.053242,0.004331,-0.182658,-0.034498
2,0.081866,0.003673,-0.039060,0.166663,-0.060628,-0.056427,0.204637,-0.168838,-0.068856,0.214044,...,-0.044647,0.011525,-0.315707,-0.082841,0.011519,-0.209255,-0.069801,-0.000003,-0.184926,-0.051607

## Formatage/encoding target y

In [24]:
y = df['target']
y.head(3)

0    a
1    a
2    a
Name: target, dtype: object

In [26]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)
y_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Proportion/distribution des classes

In [28]:
y.unique()

array(['a', 'c', 'b'], dtype=object)

In [29]:
# Dispersion des classes dans le DF d'origine
round(df[['target']].groupby(df['target']).count().rename(columns={'target': '%'}) / len(df['target']), 2)

           %
target
a       0.33
b       0.33
c       0.33

## Modelisation

### Split

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=.30, random_state=1, stratify=y)

### Check proportion/distibution dans Train/test

In [33]:
# Dispersion des classes dans y_train
y_train_temp = pd.DataFrame(y_train)
y_train_temp['%'] = 1
round(y_train_temp[['%']].groupby(y_train_temp[0]).count() / len(y_train_temp[['%']]), 2)

      %
0
0  0.33
1  0.33
2  0.33

In [34]:
# Dispersion des classes dans y_test
y_test_temp = pd.DataFrame(y_test)
y_test_temp['%'] = 1
round(y_test_temp[['%']].groupby(y_test_temp[0]).count() / len(y_test_temp[['%']]), 2)

      %
0
0  0.33
1  0.33
2  0.33

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.callbacks import EarlyStopping

2023-06-21 00:47:30.768362: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

# RESULTAT DE CE MODELE : ACCURACY @ 100% et LOSS @ 0.004

# Pour le moment, calibrÃ© avec les lettres A, B et C uniquement

In [39]:
thierry_model_LSTM = Sequential()

thierry_model_LSTM.add(LSTM(128, return_sequences=True, activation='relu', input_shape=(60,1)))
thierry_model_LSTM.add(LSTM(64, return_sequences=True, activation='relu'))
thierry_model_LSTM.add(LSTM(32, return_sequences=True, activation='relu'))
thierry_model_LSTM.add(LSTM(26, return_sequences=False, activation='relu'))
thierry_model_LSTM.add(Dense(26, activation='relu'))
thierry_model_LSTM.add(Dense(16, activation='relu'))
thierry_model_LSTM.add(Dense(3, activation='softmax'))

#model.compile(loss='mse', optimizer=Adam(learning_rate=0.5), metrics=['mae'])
thierry_model_LSTM.compile(loss='sparse_categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

es = EarlyStopping(patience=7, restore_best_weights=True)

history = thierry_model_LSTM.fit(
    X_train, y_train, 
    #validation_data=(X_test, y_test),
    validation_split = 0.3,
    callbacks=[es],
    epochs=100, batch_size=16, verbose=1)

thierry_model_LSTM.evaluate(X_test, y_test, verbose = 1)

Epoch 1/100
20/20 [==============================] - 20s 324ms/step - loss: 1.0994 - accuracy: 0.3344 - val_loss: 1.0981 - val_accuracy: 0.3158
Epoch 2/100
20/20 [==============================] - 5s 264ms/step - loss: 1.0973 - accuracy: 0.3766 - val_loss: 1.0983 - val_accuracy: 0.3459
Epoch 3/100
20/20 [==============================] - 11s 510ms/step - loss: 1.0949 - accuracy: 0.4221 - val_loss: 1.0924 - val_accuracy: 0.4436
Epoch 4/100
20/20 [==============================] - 9s 454ms/step - loss: 1.7000 - accuracy: 0.5000 - val_loss: 1.0393 - val_accuracy: 0.6015
Epoch 5/100
20/20 [==============================] - 8s 413ms/step - loss: 0.9774 - accuracy: 0.6396 - val_loss: 0.9311 - val_accuracy: 0.6316
Epoch 6/100
20/20 [==============================] - 9s 469ms/step - loss: 0.8768 - accuracy: 0.6461 - val_loss: 0.8159 - val_accuracy: 0.6466
Epoch 7/100
20/20 [==============================] - 8s 419ms/step - loss: 0.8238 - accuracy: 0.6558 - val_loss: 1.5135 - val_accuracy: 0.4436
Epoch 8/100
20/20 [==============================] - 9s 429ms/step - loss: 0.8843 - accuracy: 0.6104 - val_loss: 1.0344 - val_accuracy: 0.3985
Epoch 9/100
20/20 [==============================] - 6s 297ms/step - loss: 0.9634 - accuracy: 0.6266 - val_loss: 0.9154 - val_accuracy: 0.5113
Epoch 10/100
20/20 [==============================] - 5s 254ms/step - loss: 0.7347 - accuracy: 0.6558 - val_loss: 0.5732 - val_accuracy: 0.7293
Epoch 11/100
20/20 [==============================] - 5s 233ms/step - loss: 0.6436 - accuracy: 0.6786 - val_loss: 0.7805 - val_accuracy: 0.5263
Epoch 12/100
20/20 [==============================] - 5s 263ms/step - loss: 1.0027 - accuracy: 0.6981 - val_loss: 0.8092 - val_accuracy: 0.8120
Epoch 13/100
20/20 [==============================] - 6s 284ms/step - loss: 0.7600 - accuracy: 0.7760 - val_loss: 0.6969 - val_accuracy: 0.7669
Epoch 14/100
20/20 [==============================] - 5s 244ms/step - loss: 0.6219 - accuracy: 0.7045 - val_loss: 0.8113 - val_accuracy: 0.4812
Epoch 15/100
20/20 [==============================] - 5s 233ms/step - loss: 0.5991 - accuracy: 0.6981 - val_loss: 0.4586 - val_accuracy: 0.8195
Epoch 16/100
20/20 [==============================] - 5s 263ms/step - loss: 0.8125 - accuracy: 0.7987 - val_loss: 0.5510 - val_accuracy: 0.8120
Epoch 17/100
20/20 [==============================] - 6s 292ms/step - loss: 0.5285 - accuracy: 0.7760 - val_loss: 0.5241 - val_accuracy: 0.7519
Epoch 18/100
20/20 [==============================] - 7s 339ms/step - loss: 0.6235 - accuracy: 0.7435 - val_loss: 0.4021 - val_accuracy: 0.8195
Epoch 19/100
20/20 [==============================] - 21s 1s/step - loss: 3.2373 - accuracy: 0.6786 - val_loss: 0.5567 - val_accuracy: 0.7895
Epoch 20/100
20/20 [==============================] - 16s 812ms/step - loss: 0.4570 - accuracy: 0.8701 - val_loss: 0.3559 - val_accuracy: 0.8797
Epoch 21/100
20/20 [==============================] - 13s 643ms/step - loss: 0.4365 - accuracy: 0.8636 - val_loss: 0.4037 - val_accuracy: 0.8271
Epoch 22/100
20/20 [==============================] - 16s 791ms/step - loss: 0.5462 - accuracy: 0.8344 - val_loss: 0.4500 - val_accuracy: 0.8496
Epoch 23/100
20/20 [==============================] - 13s 648ms/step - loss: 0.4804 - accuracy: 0.8214 - val_loss: 0.4269 - val_accuracy: 0.9098
Epoch 24/100
20/20 [==============================] - 11s 538ms/step - loss: 0.4626 - accuracy: 0.8182 - val_loss: 0.4525 - val_accuracy: 0.7895
Epoch 25/100
20/20 [==============================] - 13s 632ms/step - loss: 0.7283 - accuracy: 0.7597 - val_loss: 0.7214 - val_accuracy: 0.6391
Epoch 26/100
20/20 [==============================] - 10s 470ms/step - loss: 0.5167 - accuracy: 0.7662 - val_loss: 0.4038 - val_accuracy: 0.8346
Epoch 27/100
20/20 [==============================] - 9s 458ms/step - loss: 0.4099 - accuracy: 0.8149 - val_loss: 0.2649 - val_accuracy: 0.9023
Epoch 28/100
20/20 [==============================] - 7s 364ms/step - loss: 0.4352 - accuracy: 0.8442 - val_loss: 0.4039 - val_accuracy: 0.7970
Epoch 29/100
20/20 [==============================] - 6s 323ms/step - loss: 0.4466 - accuracy: 0.8831 - val_loss: 0.3995 - val_accuracy: 0.8120
Epoch 30/100
20/20 [==============================] - 6s 312ms/step - loss: 0.3636 - accuracy: 0.8734 - val_loss: 0.1647 - val_accuracy: 0.9774
Epoch 31/100
20/20 [==============================] - 7s 335ms/step - loss: 0.8248 - accuracy: 0.7760 - val_loss: 0.5158 - val_accuracy: 0.7970
Epoch 32/100
20/20 [==============================] - 6s 323ms/step - loss: 0.3808 - accuracy: 0.8766 - val_loss: 0.2531 - val_accuracy: 0.9323
Epoch 33/100
20/20 [==============================] - 6s 310ms/step - loss: 0.2705 - accuracy: 0.9416 - val_loss: 0.1383 - val_accuracy: 0.9774
Epoch 34/100
20/20 [==============================] - 6s 319ms/step - loss: 0.2968 - accuracy: 0.9026 - val_loss: 0.1804 - val_accuracy: 0.9248
Epoch 35/100
20/20 [==============================] - 7s 331ms/step - loss: 0.2889 - accuracy: 0.9318 - val_loss: 0.8322 - val_accuracy: 0.6541
Epoch 36/100
20/20 [==============================] - 8s 422ms/step - loss: 0.1604 - accuracy: 0.9513 - val_loss: 0.0819 - val_accuracy: 0.9624
Epoch 37/100
20/20 [==============================] - 13s 651ms/step - loss: 0.9147 - accuracy: 0.9416 - val_loss: 0.1400 - val_accuracy: 0.9699
Epoch 38/100
20/20 [==============================] - 14s 696ms/step - loss: 0.3510 - accuracy: 0.9253 - val_loss: 0.1315 - val_accuracy: 0.9774
Epoch 39/100
20/20 [==============================] - 11s 545ms/step - loss: 0.0769 - accuracy: 0.9935 - val_loss: 0.0182 - val_accuracy: 1.0000
Epoch 40/100
20/20 [==============================] - 9s 451ms/step - loss: 2.1094 - accuracy: 0.9416 - val_loss: 0.1970 - val_accuracy: 0.9850
Epoch 41/100
20/20 [==============================] - 10s 476ms/step - loss: 0.1665 - accuracy: 0.9870 - val_loss: 0.1209 - val_accuracy: 1.0000
Epoch 42/100
20/20 [==============================] - 9s 435ms/step - loss: 0.0935 - accuracy: 0.9935 - val_loss: 0.0478 - val_accuracy: 0.9925
Epoch 43/100
20/20 [==============================] - 8s 409ms/step - loss: 0.1984 - accuracy: 0.9610 - val_loss: 0.0410 - val_accuracy: 1.0000
Epoch 44/100
20/20 [==============================] - 7s 367ms/step - loss: 0.0150 - accuracy: 1.0000 - val_loss: 0.0038 - val_accuracy: 1.0000
Epoch 45/100
20/20 [==============================] - 8s 386ms/step - loss: 0.4163 - accuracy: 0.9318 - val_loss: 0.0919 - val_accuracy: 0.9925
Epoch 46/100
20/20 [==============================] - 7s 338ms/step - loss: 0.0846 - accuracy: 0.9870 - val_loss: 0.0240 - val_accuracy: 0.9925
Epoch 47/100
20/20 [==============================] - 7s 331ms/step - loss: 0.2036 - accuracy: 0.9448 - val_loss: 0.0467 - val_accuracy: 0.9925
Epoch 48/100
20/20 [==============================] - 6s 309ms/step - loss: 0.1372 - accuracy: 0.9610 - val_loss: 0.0326 - val_accuracy: 0.9925
Epoch 49/100
20/20 [==============================] - 8s 379ms/step - loss: 13.4089 - accuracy: 0.9091 - val_loss: 0.3109 - val_accuracy: 0.8872
Epoch 50/100
20/20 [==============================] - 7s 325ms/step - loss: 0.1857 - accuracy: 0.9513 - val_loss: 0.1113 - val_accuracy: 0.9699
Epoch 51/100
20/20 [==============================] - 6s 303ms/step - loss: 0.0505 - accuracy: 0.9935 - val_loss: 0.0150 - val_accuracy: 1.0000
6/6 [==============================] - 1s 138ms/step - loss: 0.0046 - accuracy: 1.0000

[0.004602737724781036, 1.0]

# Sauvegarde du modÃ¨le

In [47]:
import pickle

def upload_model(model, name_of_model):
    with open(f'{name_of_model}', 'wb') as file:
        pickle.dump(model, file)


def load_model(name_of_the_model=False):
    if name_of_the_model == False:
        with open('model.randomfo', 'rb') as file:
            loaded_model = pickle.load(file)
        return loaded_model
    else:
        with open(name_of_the_model, 'rb') as file:
            loaded_model = pickle.load(file)
        return loaded_model

In [48]:
upload_model(thierry_model_LSTM, 'thierry_model_LSTM')

# Test avec d'autres dataset

In [53]:
#Il faut renseigner le nim du dataset ici

df_verif = load_dataset(PROJECT_ID, 'test_dataset.test7')
df_verif.head(3)

wagon-give-me-a-sign test_dataset.test7

,x_0,y_0,z_0,x_1,y_1,z_1,x_2,y_2,z_2,x_3,...,x_18,y_18,z_18,x_19,y_19,z_19,x_20,y_20,z_20,target
0,0.0,0.0,0.0,0.068996,-0.001794,-0.026495,0.129794,-0.049328,-0.037758,0.157946,...,0.015763,-0.236859,-0.053696,0.014897,-0.160986,-0.042879,0.003309,-0.143430,-0.028293,a
1,0.0,0.0,0.0,0.084189,-0.004527,-0.035077,0.159894,-0.063521,-0.049802,0.195749,...,0.022846,-0.301951,-0.067628,0.019003,-0.205834,-0.053242,0.004331,-0.182658,-0.034498,a
2,0.0,0.0,0.0,0.081866,0.003673,-0.039060,0.166663,-0.060628,-0.056427,0.204637,...,0.011525,-0.315707,-0.082841,0.011519,-0.209255,-0.069801,-0.000003,-0.184926,-0.051607,a

In [54]:
X_verif = df_verif.drop(columns=['x_0', 'y_0', 'z_0', 'target'])
y_verif = df_verif['target']
y_verif_encoded = encoder.transform(y_verif)

In [55]:
model_verif = load_model('thierry_model_LSTM')

In [56]:
model_verif.evaluate(X_verif, y_verif_encoded, verbose = 1)

20/20 [==============================] - 4s 74ms/step - loss: 0.0036 - accuracy: 1.0000

[0.003587659215554595, 1.0]

# RESULTAT OK : ACCURACY @ 100%